#!/usr/bin/env python3
import os
import sys
from helpers import get_user_timeline
from termcolor import colored
from analyzer import Analyzer

def assign_color(score):
    if score == 0:
        return "yellow"
    elif score > 0:
        return "green"
    return "red"

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    screen_name = sys.argv[1]
    tweets = get_user_timeline(screen_name, count=50)
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    for tweet in tweets:
        score = analyzer.analyze(tweet)
        print(colored('{} {}'.format(score, tweet), assign_color(score)))

if __name__ == '__main__':
    main()